### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by onearmfrog** [jkphl/grunt-iconizr#10]
Hey,

The Iconizr task kept freezing so I managed to debug it and I got:
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

Have you ever come across this?

Thanks

**Comment by jkphl** [comment]
Hi @onearmfrog,

as you did never respond to this issue anymore, I'll close this for now. Please feel free to re-open if you've still got problems.

Thanks, cheers,
Joschi
