### ISSUE TITLE
pngcrush: Syntax error

### ISSUE THREAD

**Issue by jepek** [jkphl/grunt-iconizr#14]
Problem: http://recordit.co/q9h3Ay7iwu

My config: https://gist.github.com/jepek/a2521a122e90cf554386

Anyone have idea what's wrong?

**Comment by jkphl** [comment]
Hi @jepek,

this might have been a problem with an [outdated pngcrush-depenency](https://github.com/jkphl/node-iconizr/issues/9). I just released an updated version. Could you please check if this works for you now? I'll close the issue, but please feel free to re-open it if you've still got problems.

Cheers & Happy New Year,
Joschi
