### ISSUE TITLE
Error: Start tag expected on Adobe Illustrator SVG files.

### ISSUE THREAD

**Issue by augbog** [jkphl/grunt-iconizr#20]
I tried running grunt-iconizr on some SVGs a designer was sending me and it throws an unexpected start tag error. 

![screen shot 2014-11-04 at 11 44 47 am](https://cloud.githubusercontent.com/assets/2054339/4906689/14d9c1b4-645b-11e4-9048-b0d5ba18de82.png)

I believe it's because Adobe Illustrator adds a bunch of XML content.

    <?xml version="1.0" encoding="utf-8"?>
    
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [
	<!ENTITY ns_extend "http://ns.adobe.com/Extensibility/1.0/">
	<!ENTITY ns_ai "http://ns.adobe.com/AdobeIllustrator/10.0/">
	<!ENTITY ns_graphs "http://ns.adobe.com/Graphs/1.0/">
	<!ENTITY ns_vars "http://ns.adobe.com/Variables/1.0/">
	<!ENTITY ns_imrep "http://ns.adobe.com/ImageReplacement/1.0/">
	<!ENTITY ns_sfw "http://ns.adobe.com/SaveForWeb/1.0/">
	<!ENTITY ns_custom "http://ns.adobe.com/GenericCustomNamespace/1.0/">
	<!ENTITY ns_adobe_xpath "http://ns.adobe.com/XPath/1.0/">
    ]>
    <svg version="1.1" id="Layer_1" xmlns:x="&ns_extend;" xmlns:i="&ns_ai;" xmlns:graph="&ns_graphs;"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 85.3 85.4"
	 enable-background="new 0 0 85.3 85.4" xml:space="preserve">
    ...

Is there anyway we can get grunt-iconizr to work with this? Or if people have workarounds, maybe I am just doing something wrong. Would love to incorporate this in our workflow. Thanks a bunch.

**Comment by jkphl** [comment]
Hi @augbog,

did you ever manage to get this working? I'll start to rewrite iconizr from scratch in the next few days. If you're still interested, you could [send me the files](mailto:joschi@kuphal.net) in question and I'll see what I can do / say. Besides that, I'll close this issue for now, but please feel free to re-open it in case you still have problems.

Cheers & Happy New Year,
Joschi
