### ISSUE TITLE
Referenced File Names Do Not Match Generated File Names

### ISSUE THREAD

**Issue by hguiney** [jkphl/grunt-iconizr#22]
iconizr: {
      svg2sprites: {
        src: ['<%= conf.bg.images %>/svg'],
        dest: '<%= conf.bg.styles %>/_iconizr',
        options: {
          prefix: 'bg',
          verbose: 3,
          render: {
            css: false,
            scss: '.',
          } // render
        } // options
      } // svg2sprites
    } // iconizr

Result:

```
<script type="text/javascript">!function(){var e=window,t=e.document,a=arguments,n="createElementNS",s="http://www.w3.org/",A="svg",r=function(e){var r=t.getElementsByTagName("script")[0],g=t.createElement("link");g.rel="stylesheet",g.type="text/css",g.href=a[4]+a[1*e|2*(t[n]&&t[n](s+"2000/"+A,A).createSVGRect&&t.implementation.hasFeature(s+"TR/SVG11/feature#Image","1.1"))],r.parentNode.insertBefore(g,r)},g=new e.Image;g.onerror=function(){r(0)},g.onload=function(){r(1===g.width&&1===g.height)},g.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="}("bg-png-sprite.css","bg-png-data.css","bg-svg-sprite.css","bg-svg-data.css","/eomdb/SysConfig/WebPortal/BostonGlobe/Framework/styles/_iconizr/");</script><noscript><link href="/eomdb/SysConfig/WebPortal/BostonGlobe/Framework/styles/_iconizr/bg-png-sprite.css" rel="stylesheet" type="text/css" media="all"></noscript>
```
Note the file names in the tester are bg-png-sprite.css, etc. based on the specified prefix. But the actual source files are called _iconizr-png-sprite.scss, etc. which seem to get their prefix from the parent directory. Also, with the leading underscore, they wouldn't get turned into individual files.

Additionally, all of the scss files get placed one level behind the one specified in `dest`. So `_iconizr-png-sprite.scss` gets put under `styles`, with the background values set to `url(icons/icons.png);`. But the `icons` folder is within `_iconizr`, not `styles`.

**Comment by jkphl** [comment]
Hi @hguiney,

as you didn't respond to this any further, I assume you solved your name translation troubles and close this issue for now. Please feel free to re-open in case you still have problems.

Cheers,
Joschi
