### ISSUE TITLE
Strange error on Travis CI

### ISSUE THREAD

**Issue by yoyurec** [jkphl/grunt-iconizr#23]
Locally all is Ok, but when i run it on TravisCI i got errors.
Do 'grunt-iconizr' has some system software requirements?

**>npn install --loglevel info**:

```
...
npm info postinstall svg-sprite@0.3.2
npm ERR! cb() never called!
npm ERR! not ok code 0
...
```

**Comment by yoyurec** [comment]
looking to `svg-sprite@0.3.2` i hope it won't reproduce with 1.x version...
when is next `grunt-iconizr` release? :flushed:

**Comment by jkphl** [comment]
Hi @yoyurec,

not that I'd know. Sorry, I don't think I can help you here, as the error message is not really helpful. Unfortunately, I did never run the "old" versions of _node-iconizr_ or _svg-sprite_ on Travis. The new version of _svg-sprite_ [passes just fine](https://travis-ci.org/jkphl/svg-sprite), though. Please understand that -- as I'm currently working on a complete rewrite of _node-iconizr_ (and subsequently _grunt-iconizr_) -- I won't put any effort into the old versions anymore.

Cheers,
Joschi

**Comment by jkphl** [comment]
:D our messages just crossed ... We'll, if there don't arise any problems, I'd guess within the next two weeks, depending on whether I'll immediately add support for inline SVG or not (and do that shortly after the release). I'm not really decided on that right now, still figuring out the most reasonable approach.

**Comment by yoyurec** [comment]
> within the next two weeks

I was hoping in 2h )))
sitting here and refreshing repo page

is possible to do legacy release of `grunt-iconizr` with new `svg-sprite` in dependency, but without new features support?

**Comment by jkphl** [comment]
Unfortunately that's impossible. _svg-sprite_ has been rewritten from scratch and the API changed **completely**, there's no way the two would work together. Sorry, but you'll have to wait for the new generation. I'll keep you posted! ;)

**Comment by yoyurec** [comment]
:+1:

**Comment by yoyurec** [comment]
it's _NPM_, needed **2.x** version! (_Travis CI_ uses **1.x** by default)
https://stackoverflow.com/questions/26474640/why-travisci-builds-fails-during-npm-install-due-to-file-lock

```
...
before_script:
  - npm install -g npm@2
...
```

maybe you should add it to readme file...

**Comment by jkphl** [comment]
Ah, good to know, thanks for the heads-up. Will add it to the README tomorrow! :+1:

**Comment by jkphl** [comment]
In fact, when I have a look at the [`.travis.yml` of the latest _svg-sprite_](https://github.com/jkphl/svg-sprite/blob/master/.travis.yml):

``` yml
...
before_install:
  - npm update -g npm
...
```

On the other hand, I'm not sure if this is really something that should be part of _grunt-iconizr_'s README. In fact, it's _svg-sprite_ that has this requirement, and there are probably way more modules out there requiring _NPM 2_. I've never seen a hint specifically for Travis users in a module's READMEs, and somehow I get the impression that this is a rather generic topic which could also be seen as base knowledge for devs using Travis CI, don't you think?

**Comment by yoyurec** [comment]
> In fact, when I have a look at the .travis.yml of the latest svg-sprite

yes, but i'm not testing `svg-sprite`, i'm testing my private repo with `grunt-iconizr` (which uses `svg-sprite`) in dependencies...
so i should to be noticed in readme to use in my `.travis.yml` config latest NPM to get grunt-iconizr works properly.

..on other hand, you are right - it's a dev knowledge and experience: **"use latest NPM on local machine & 'Travis CI' in own projects to be sure that all is OK"** :sparkles:

**Comment by yoyurec** [comment]
Another reason to add info - you already doing it: 

> This plugin requires Grunt ~0.4.2

**Comment by jkphl** [comment]
> use latest NPM on local machine & 'Travis CI' in own projects to be sure that all is OK

Sounds reasonable and ist not too much to clutter the README. Will do that!

> This plugin requires Grunt ~0.4.2

... standard text inserted by `grunt-init gruntplugin`, nothing I did write on my own. ;)
