### ISSUE TITLE
Possibility to scale output sprite(s) with a multiplier ?

### ISSUE THREAD

**Issue by sblancho** [jkphl/grunt-iconizr#25]
Hi, 
I tried grunt-iconizr with 10 SVG 100x100 pixels, which gave me a output sprite of 100x1000 pixels !
Is it possible to config the output sprite's dimensions with a multiplier of 0.75 for example, in order to have a 75x750 pixels output sprite ??
If yes, how to do that ?
Thanks in advance.
PS: Sorry if i post on the wrong place.

**Comment by jkphl** [comment]
Did you try specifying `maxwidth = 75`, which should downscale your icons and thus the whole sprite appropriately?

**Comment by sblancho** [comment]
Hi Josch,
It works perfectly !
The documentation is not very explicit, i think (or it's my misunderstanding ?) 

<table><tr>
<td><code>maxwidth</code></td>
<td>Integer</td>
<td>Maximum width of single SVG images. Will be downscaled if necessary. Defaults to <code>1000</code>.</td>
</tr>
</table>

Thanks for your answer !
You can close the "issue" :-)

**Comment by jkphl** [comment]
You're welcome! :)
