### ISSUE TITLE
Can it generate png with doubled size (2x)?

### ISSUE THREAD

**Issue by nicksyndicate** [jkphl/grunt-iconizr#27]
Hi @jkphl .

If there any option for generating png sprites with 2x, 3x sizes ?

Thanks.

**Comment by jkphl** [comment]
Hey @nicksyndicate,

the current (old) generation of node-iconizr doesn't support PNG scaling, sorry. The upcoming version will have that feature, though, due for release within the next two weeks.

Cheers,
Joschi
