### ISSUE TITLE
Fails to install with latest phantomjs 1.x

### ISSUE THREAD

**Issue by joaoponceleao** [jkphl/grunt-iconizr#28]
Hi,
I've managed to lose my grunt-iconizr install, and can't get it back.
It fails to compile and I've tracked down the problem to a couple of dependencies.
Specifically, `weak@0.2.2` which has problems with `node-gyp rebuild`. This is quite an outdated version of `weak` and later versions have no problems compiling. This seems to be a dependency of `dnode`, which itself is a dependency of: `phantom<----phantom-sync<----svg-sprite<----iconizr<----grunt-iconizr`.
Anything I can do to solve this and get iconizr back?

Related: I used to have `phantomjs192` installed in the system, and `phantom-sync` installed globally. This was the only way of getting iconizr to install. Phantom-sync is no longer happy with 1.9.2 and requires a later version (1.15+). This is fine, but it means it will install phantomjs in node directly (giving me problems with libxmljs) or if I upgrade phantomjs, phantom-sync fails to install globally (giving me the above issues ( `weak@0.2.2` from `dnode`).
This is a bit of a dependency nightmare, but everything was fine a few days ago....

**Comment by jkphl** [comment]
Hey @joaoponceleao,

I'm very sorry to say this but I'm not able to help you with your problem. I have no idea what to do in this situation, but I know that `libxmljs` respectively `node-gyp` tends to cause problems — which is the main reason why I removed these dependencies in the latest version of [svg-sprite](https://github.com/jkphl/svg-sprite) (which _grunt-iconizr_ is based on). I'm currently working on a new version of _node-iconizr_ (and _grunt-iconizr_) and plan to release it within the next two weeks. The problem should be gone then. Please have some patience.

Cheers,
Joschi

**Comment by joaoponceleao** [comment]
No worries,
I put up the issue in case someone (or me) find a solution, but also, in the hope that some of the dependencies could go away in the next version ;-)

**Comment by joaoponceleao** [comment]
Ok. So managed to find an acceptable solution while waiting for the new version. This might break other modules but iconizr is happy.
Basically, reverting to node 0.10.x takes care of everything. I was not able to install this on node 0.11 or 0.12.
