### ISSUE TITLE
No CSS created

### ISSUE THREAD

**Issue by phlorie** [jkphl/grunt-iconizr#29]
Hi

I am using Mac OS 10.9.5.
I had an issue while installing with grunt.

``` shell
> weak@0.2.2 install /private/var/www/js-client-ui/node_modules/grunt-iconizr/node_modules/iconizr/node_modules/svg-sprite/node_modules/phantom-sync/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild

  CXX(target) Release/obj.target/weakref/src/weakref.o
  SOLINK_MODULE(target) Release/weakref.node
  SOLINK_MODULE(target) Release/weakref.node: Finished
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-iconizr" "--save-dev"
npm ERR! node v0.10.36
npm ERR! npm  v2.3.0
npm ERR! path /private/var/www/js-client-ui/node_modules/grunt-iconizr/node_modules/iconizr/node_modules/pngquant-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/strip-dirs/node_modules/is-absolute
npm ERR! code EMFILE
npm ERR! errno 20

npm ERR! EMFILE, readdir '/private/var/www/js-client-ui/node_modules/grunt-iconizr/node_modules/iconizr/node_modules/pngquant-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/strip-dirs/node_modules/is-absolute'
```

Now it just generates the svg and png files but no CSS nor HTML, with the error:

``` shell
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
```

npm version : 2.3.0
grunt version : 0.4.5
node version:  0.10.36

Thank you for your help

**Comment by jkphl** [comment]
Hey @phlorie,

I'm very sorry but I fear I can't help you too much with this. The log snippet makes me thing you could have a problem with either
- libxmljs (node-gyp),
- phantomjs or
- **pngcrush** (most likely).

Could you please try to disable PNG optimization by setting the `level` config option to `0`? Does this change anything?

There's a new major version of `grunt-iconizr` on its way with far less dependencies, but it will take me another week or two to finalize it. Maybe this may also solve your problem.

Cheers,
Joschi

**Comment by phlorie** [comment]
Thank you for the quick answer. 
I thought it might come from the dependencies. 
I can wait for the next version. I am looking forward to it because I am very interested in your tool which seems amazing and really corresponds to what I am looking for.

**Comment by jkphl** [comment]
You're welcome.

If you are up for it (and know how to do it): The development versions of [grunt-iconizr](https://github.com/jkphl/grunt-iconizr/tree/dev) and the underlying [node-iconizr](https://github.com/jkphl/node-iconizr/tree/dev) can be found in dedicated development branches here on Github. But please be warned: There's no proper documentation yet ([this README](https://github.com/jkphl/node-iconizr/blob/dev/README.md) is your best bet so far) and it's not properly tested (although we use it internally already). Unfortunately I can't give any support for it at the moment (way too overloaded this week), so you'd be on your own for now. ;)

**Comment by phlorie** [comment]
Unfortunately, I have no idea how to work on a grunt plugin.

I just tried the level 0 option and the files were generated properly I think. So while I wait for the next version, this will do.
Only the automatic detection is failing in the preview. ( a '/' is missing in the script to have a proper path to css file).
Also, too bad the path to the images is relative in the generated Sass and LESS files, it requires to be overwritten.

Another question :
I started working with grunticon when I found your project so I am very interested about customising SVG icons, changing colors for example. The use of the svgsprite inline.svg option isn't clear, it doesn't seem to be well integrated with the rest.
There might be a way of extracting the fill attribute from the svg into the CSS (or else), and then create new classes to change that color.
The goal for me here is to have a sprite and still be able to change icon colors (for hover behaviour for example).
I am sorry, I know that's a lot of things, but I thought I might as well just use this as feedback too.
Thanks

**Comment by jkphl** [comment]
> Also, too bad the path to the images is relative in the generated Sass and LESS files, it requires to be overwritten.

Not sure if this helps, but the paths in the Sass and LESS files _should_ be as they are expected to be in the final CSS file (relative from the CSS to the sprite). It's your responsibility to ensure that the compiled Sass / LESS results are put at the correct location in the end.

> The use of the svgsprite inline.svg option isn't clear, it doesn't seem to be well integrated with the rest.

That's true. I added support for the inline sprite format at a late stage and the only thing it does is rendering a sprite variant that is _suitable_ for inlining it into an HTML document, nothing more and nothing less. Everything else is up to you.

The upcoming release of (grunt-/gulp-)iconizr is based on the new generation of [svg-sprite](https://github.com/jkphl/svg-sprite) and offers a lot of new options. But still, it doesn't feature real support for inline SVG (as grunticon does in the meantime). However, I'm planning to implement this in a second step (with some additional features). Due to my horrible workload these days this will take me some more time though.

**Comment by phlorie** [comment]
Thank you for answering all of that.

Just about the path for the sprites, I think it would be great if we were able to customise that path because architecture may differ across projects, and I like to separate CSS from JS and images and sometimes images can be in deeper folders.

**Comment by jkphl** [comment]
As I said, the next generation of iconizr will feature a whole new way of specifying all those paths. Let's continue this conversation as soon as it's released and you had the chance to take a look at it. Happy spriting! ;)
