### ISSUE TITLE
Installation fails on OS X

### ISSUE THREAD

**Issue by dawidk92** [jkphl/grunt-iconizr#32]
After sudo npm install grunt-iconizr terminal outputs me this errors:

``` javascript
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Work/Targi_Smaku/node_modules/grunt-iconizr/node_modules/iconizr/node_modules/svg-sprite/node_modules/phantom-sync/node_modules/phantom/node_modules/dnode/node_modules/weak
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```

I'm using:
OS X 10.10.4
npm 2.12.1
phantomjs 2.0.0
grunt 0.4.5
grunt-iconizr 0.2.3

npm-debug.log -> https://gist.githubusercontent.com/dawidk92/1d333f13d77a6c3ed9e6/raw/gistfile1.js

**Comment by jkphl** [comment]
Hey @dawidk92,

this seems to be a long-term problem with the _libxmljs_ dependency on the Mac, please see [for example here](https://github.com/jkphl/grunt-iconizr/issues/4) for one of the issues regarding this. I don't know any fix, I'm sorry.

However, there's a new generation of _node-iconizr_ respectively _grunt-iconizr_ in the [dev branch](https://github.com/jkphl/grunt-iconizr/tree/dev) that doesn't have the _libxmljs_ dependency anymore. Unfortunately, the new version is only poorly documented so far and I won't have the time to finally push it out the door before August. You may give it a try, however.

Good luck and cheers,
Joschi

**Comment by jonasva** [comment]
same issue here on Ubuntu with node v5.9.1 and npm 3.8.2

**Comment by jkphl** [comment]
@jonasva Did you try the most recent version as decribed in the [previous comment](https://github.com/jkphl/grunt-iconizr/issues/32#issuecomment-119526495)?
